import json
import re

source_ts = r"c:\Users\bayta\OneDrive\Masaüstü\fitness\scratch_foods.ts"
dest_json = r"c:\Users\bayta\OneDrive\Masaüstü\fitness\src\locales\de.json"

translations = {
    '251': ('Tofu (fest)', 'Sojaprodukt mit hohem Proteingehalt.'),
    '252': ('Tempeh', 'Fermentiertes Sojaprodukt.'),
    '253': ('Seitan', 'Fleischersatz aus Weizengluten.'),
    '254': ('Edamame', 'Junge Sojabohnen.'),
    '255': ('Linsen', 'Hülsenfrucht reich an Ballaststoffen.'),
    '256': ('Kichererbsen', 'Garbanzobohnen.'),
    '257': ('Schwarze Bohnen', 'Beliebte Hülsenfrucht.'),
    '258': ('Quinoa', 'Vollständiges pflanzliches Protein.'),
    '259': ('Chia-Samen', 'Samen mit hohem Ballaststoffgehalt.'),
    '260': ('Hanfherzen', 'Reich an Omega-3-Fettsäuren.'),
    '261': ('Hefeflocken', 'Käsiger veganer Geschmack.'),
    '262': ('Sojamilch', 'Milchfreie Alternative.'),
    '263': ('Hafermilch', 'Cremige vegane Milch.'),
    '264': ('Erbsenproteinisolat', 'Pflanzliches Proteinpulver.'),
    '265': ('Falafel', 'Frittierte Kichererbsenbällchen.'),
    '266': ('Hummus', 'Kichererbsen-Dip.'),
    '267': ('Veganer Burger-Patty', 'Pflanzliches Fleisch.'),
    '268': ('Jackfrucht', 'Fleischtextur-Ersatz.'),
    '269': ('Mandelmus', 'Nussmus-Aufstrich.'),
    '270': ('Cashew-Käse', 'Vegane Käsealternative.'),
    '271': ('Beyond Burger Patty', 'Beliebter veganer Burger.'),
    '272': ('Impossible Burger Patty', 'Pflanzliche Fleischalternative.'),
    '273': ('Vegane Wurst', 'Pflanzliche Wurst.'),
    '274': ('Veganer Speck', 'Rauchige vegane Streifen.'),
    '275': ('Vegane Mayo', 'Eifreie Mayonnaise.'),
    '276': ('Agavendicksaft', 'Veganer Süßstoff.'),
    '277': ('Ahornsirup', 'Natürlicher Sirup.'),
    '278': ('Sojajoghurt', 'Milchfreier Joghurt.'),
    '279': ('Kokosjoghurt', 'Cremiger veganer Joghurt.'),
    '280': ('Macadamiamilch', 'Nussmilch.'),
    '281': ('Cashewmilch', 'Kalorienarme Nussmilch.'),
    '282': ('Kokosmilch (Dose)', 'Reichhaltige kulinarische Milch.'),
    '283': ('Mandelmilch (ungesüßt)', 'Kalorienarme Milchalternative.'),
    '284': ('Kidneybohnen', 'Rote Bohnen.'),
    '285': ('Weiße Bohnen (Navy)', 'Weiße Bohnen.'),
    '286': ('Pintobohnen', 'Wachtelbohnen.'),
    '287': ('Cannellini-Bohnen', 'Große weiße Bohnen.'),
    '288': ('Great Northern Bohnen', 'Mittlere weiße Bohnen.'),
    '289': ('Limabohnen', 'Mondbohnen.'),
    '290': ('Ackerbohnen', 'Saubohnen.'),
    '291': ('Avocado', 'Reich an gesunden Fetten.'),
    '292': ('Macadamianüsse', 'Fettreiche Keto-Nuss.'),
    '293': ('Pekannüsse', 'Keto-freundliche Nuss.'),
    '294': ('Paranüsse', 'Reich an Selen.'),
    '295': ('Oliven', 'Gesunde Fettquelle.'),
    '296': ('Kokosöl', 'Reine Fettquelle.'),
    '297': ('MCT-Öl', 'Mittelkettige Triglyceride.'),
    '298': ('Ghee', 'Geklärte Butter.'),
    '299': ('Speck', 'Knuspriges Schweinefett.'),
    '300': ('Schweineschwarten', 'Frittierte Schweinehaut.'),
    '301': ('Lachs', 'Fetter Fisch.'),
    '302': ('Sardinen', 'Kleine fettreiche Fische.'),
    '303': ('Makrele', 'Reich an Omega-3.'),
    '304': ('Schlagsahne', 'Fettreiche Milchprodukte.'),
    '305': ('Frischkäse', 'Weicher, reichhaltiger Käse.'),
    '306': ('Brie', 'Weichkäse.'),
    '307': ('Camembert', 'Weicher französischer Käse.'),
    '308': ('Zucchini', 'Kohlenhydratarmes Gemüse.'),
    '309': ('Blumenkohl', 'Keto-Grundnahrungsmittel.'),
    '310': ('Spargel', 'Kohlenhydratarme Stangen.'),
    '311': ('Eier (ganz)', 'Nahrhafte Proteinquelle.'),
    '312': ('Ribeye-Steak', 'Fettes Rindfleischstück.'),
    '313': ('Avocadoöl', 'Öl für hohe Hitze.'),
    '314': ('Olivenöl', 'Herzgesundes Öl.'),
    '315': ('Walnussöl', 'Nussiges Öl.'),
    '316': ('Sesamöl', 'Aromatisches Speiseöl.'),
    '317': ('Leinöl', 'Reich an ALA-Omega-3.'),
    '318': ('Kürbiskerne', 'Pepitas.'),
    '319': ('Sonnenblumenkerne', 'Nahrhafte Samen.'),
    '320': ('Pinienkerne', 'Pignoli.'),
    '321': ('Pistazien', 'Grüne Nüsse.'),
    '322': ('Haselnüsse', 'Filberts.'),
    '323': ('Cheddar-Käse', 'Würziger Käse.'),
    '324': ('Schweizer Käse', 'Löchriger Käse.'),
    '325': ('Provolone', 'Italienischer Käse.'),
    '326': ('Gouda', 'Holländischer Käse.'),
    '327': ('Havarti', 'Dänischer Käse.'),
    '328': ('Pepper Jack', 'Würziger Käse.'),
    '329': ('Feta-Käse', 'Krümeliger Käse.'),
    '330': ('Ziegenkäse', 'Chevre.'),
    '331': ('Sushi-Rolle', 'Gemischtes Sushi.'),
    '332': ('Pad Thai', 'Thailändisches Nudelgericht.'),
    '333': ('Chicken Tikka Masala', 'Indisches Curry.'),
    '334': ('Rindfleisch-Taco', 'Mexikanischer Taco.'),
    '335': ('Burrito', 'Großer Wrap.'),
    '336': ('Pho', 'Vietnamesische Suppe.'),
    '337': ('Ramen', 'Japanische Nudelsuppe.'),
    '338': ('Dim Sum', 'Chinesische Teigtaschen.'),
    '339': ('Samosa', 'Frittierte Teigtasche.'),
    '340': ('Gyros', 'Griechischer Fleisch-Wrap.'),
    '341': ('Moussaka', 'Griechischer Auflauf.'),
    '342': ('Paella', 'Spanisches Reisgericht.'),
    '343': ('Fajitas', 'Gegrilltes Fleisch und Paprika.'),
    '344': ('Enchiladas', 'Gerollte Tortillas.'),
    '345': ('Churros', 'Frittierter Teig.'),
    '346': ('Naan-Brot', 'Indisches Fladenbrot.'),
    '347': ('Bibimbap', 'Koreanische Rice Bowl.'),
    '348': ('Kimchi', 'Fermentierter Kohl.'),
    '349': ('Gnocchi', 'Kartoffelklößchen.'),
    '350': ('Lasagne', 'Geschichtete Pasta.'),
    '351': ('Tom Yum', 'Scharfe thailändische Suppe.'),
    '352': ('Butter Chicken', 'Cremiges indisches Gericht.'),
    '353': ('Chicken Shawarma', 'Nahöstlicher Wrap.'),
    '354': ('Lammkebab', 'Gegrilltes Lamm.'),
    '355': ('Rindfleisch-Kofta', 'Gewürzte Fleischbällchen.'),
    '356': ('Pita-Brot', 'Fladenbrot.'),
    '357': ('Tzatziki', 'Joghurt-Dip.'),
    '358': ('Baba Ganoush', 'Auberginen-Dip.'),
    '359': ('Dolma', 'Gefüllte Weinblätter.'),
    '360': ('Spanakopita', 'Spinatpastete.'),
    '361': ('Baklava', 'Süßes Gebäck.'),
    '362': ('Tiramisu', 'Italienisches Dessert.'),
    '363': ('Gelato', 'Italienisches Eis.'),
    '364': ('Miso-Suppe', 'Japanische Suppe.'),
    '365': ('Wakame', 'Algensalat.'),
    '366': ('Soba-Nudeln', 'Buchweizennudeln.'),
    '367': ('Udon-Nudeln', 'Dicke Weizennudeln.'),
    '368': ('Matcha', 'Grünteepulver.'),
    '369': ('Taro', 'Wurzelgemüse.'),
    '370': ('Boba-Tee', 'Bubble Tea.'),
    '371': ('Frühlingsrolle', 'Frittierte Teigrolle.'),
    '372': ('Eierrolle', 'Chinesische Vorspeise.'),
    '373': ('Wonton-Suppe', 'Teigtaschensuppe.'),
    '374': ('Frittierte Calamari', 'Frittierter Tintenfisch.'),
    '375': ('Mozzarella-Sticks', 'Frittierter Käse.'),
    '376': ('Jalapeno Poppers', 'Gefüllte Paprika.'),
    '377': ('Tater Tots', 'Frittierte Kartoffelbällchen.'),
    '378': ('Hash Browns', 'Kartoffelpuffer.'),
    '379': ('Corn Dog', 'Würstchen im Teigmantel.'),
    '380': ('Pesto-Pasta', 'Nudeln mit Basilikumsauce.'),
    '381': ('Molkenprotein', 'Milchprotein.'),
    '382': ('Kaseinprotein', 'Langsam verdauliches Protein.'),
    '383': ('BCAA', 'Verzweigtkettige Aminosäuren.'),
    '384': ('Kreatin', 'Leistungsergänzung.'),
    '385': ('Pre-Workout', 'Energie-Boost.'),
    '386': ('Proteinriegel', 'Praktischer Snack.'),
    '387': ('Mass Gainer', 'Kalorienreiches Pulver.'),
    '388': ('Kollagenpeptide', 'Gelenkunterstützung.'),
    '389': ('Elektrolytgetränk', 'Hydratation.'),
    '390': ('Energy-Drink', 'Koffeinhaltiges Getränk.'),
    '391': ('Protein-Cookie', 'Proteinreicher Keks.'),
    '392': ('Mahlzeitenersatz-Shake', 'Ausgewogene Ernährung.'),
    '393': ('Glutamin', 'Aminosäure zur Erholung.'),
    '394': ('Fischöl', 'Omega-3-Pillen.'),
    '395': ('Multivitamin-Gummibärchen', 'Vitamine.'),
    '396': ('Quest Bar', 'Beliebter Proteinriegel.'),
    '397': ('RxBar', 'Riegel aus Vollwertkost.'),
    '398': ('Clif Bar', 'Energieriegel.'),
    '399': ('Larabars', 'Frucht- und Nussriegel.'),
    '400': ('Keto-Riegel', 'Low-Carb-Riegel.'),
    '401': ('Proteinwasser', 'Angereichertes Wasser.'),
    '402': ('Kombucha', 'Fermentierter Tee.'),
    '403': ('Cold Brew Kaffee', 'Starker Kaffee.'),
    '404': ('Grüner Tee', 'Antioxidatives Getränk.'),
    '405': ('Schwarzer Tee', 'Koffeinhaltiger Tee.'),
    '406': ('Mandelmehl', 'Keto-Backen.'),
    '407': ('Kokosmehl', 'Ballaststoffreiches Mehl.'),
    '408': ('Tapiokamehl', 'Glutenfreie Stärke.'),
    '409': ('Maniokmehl', 'Wurzelmehl.'),
    '410': ('Pfeilwurzelmehl', 'Verdickungsmittel.'),
    '411': ('Blaubeeren', 'Reich an Antioxidantien.'),
    '412': ('Erdbeeren', 'Süße Beeren.'),
    '413': ('Himbeeren', 'Ballaststoffreiche Beeren.'),
    '414': ('Brombeeren', 'Dunkle Beeren.'),
    '415': ('Mango', 'Tropische Frucht.'),
    '416': ('Ananas', 'Süße Tropenfrucht.'),
    '417': ('Kiwi', 'Viel Vitamin C.'),
    '418': ('Papaya', 'Verdauungsenzyme.'),
    '419': ('Wassermelone', 'Hydratisierende Melone.'),
    '420': ('Cantaloupe-Melone', 'Orange Melone.'),
    '421': ('Honigmelone', 'Grüne Melone.'),
    '422': ('Pfirsich', 'Steinobst.'),
    '423': ('Pflaume', 'Süße Frucht.'),
    '424': ('Kirsche', 'Kleine Frucht.'),
    '425': ('Grapefruit', 'Zitrusfrucht.'),
    '426': ('Granatapfel', 'Kernfrucht.'),
    '427': ('Feige', 'Süß und weich.'),
    '428': ('Datteln', 'Energiereiche Frucht.'),
    '429': ('Spinat', 'Blattgemüse.'),
    '430': ('Grünkohl', 'Superfood-Gemüse.'),
    '431': ('Rucola', 'Pfefferiges Blattgemüse.'),
    '432': ('Bok Choy', 'Asiatischer Kohl.'),
    '433': ('Mangold', 'Nährstoffreich.'),
    '434': ('Kohlblätter (Collard Greens)', 'Herzhaftes Grünzeug.'),
    '435': ('Rosenkohl', 'Mini-Kohl.'),
    '436': ('Brokkoli', 'Kreuzblütler.'),
    '437': ('Kohl', 'Knackiges Gemüse.'),
    '438': ('Karotten', 'Wurzelgemüse.'),
    '439': ('Rote Bete', 'Rotes Wurzelgemüse.'),
    '440': ('Radieschen', 'Scharfe Wurzel.'),
    '441': ('Weiße Rübe', 'Wurzelgemüse.'),
    '442': ('Pastinake', 'Süße Wurzel.'),
    '443': ('Süßkartoffel', 'Orange Knolle.'),
    '444': ('Yamswurzel', 'Stärkehaltige Wurzel.'),
    '445': ('Sommerkürbis', 'Sommergemüse.'),
    '446': ('Kürbis', 'Winterkürbis.'),
    '447': ('Artischocke', 'Distelknospe.'),
    '448': ('Aubergine', 'Lila Gemüse.'),
    '449': ('Gelber Kürbis', 'Sommergemüse.'),
    '450': ('Butternusskürbis', 'Süßer Winterkürbis.'),
    '451': ('Eichelkürbis', 'Winterkürbis.'),
    '452': ('Spaghettikürbis', 'Nudelalternative.'),
    '453': ('Lauch', 'Milde Zwiebel.'),
    '454': ('Frühlingszwiebeln', 'Grüne Zwiebeln.'),
    '455': ('Preiselbeeren', 'Herbe Beeren.'),
    '456': ('Stachelbeeren', 'Saure Beeren.'),
    '457': ('Passionsfrucht', 'Tropische Frucht.'),
    '458': ('Drachenfrucht', 'Pitaya.'),
    '459': ('Litschi', 'Süße Frucht.'),
    '460': ('Mangostan', 'Tropischer Genuss.'),
    '461': ('Pizzastück', 'Käse und Tomate.'),
    '462': ('Cheeseburger', 'Rindfleisch und Käse.'),
    '463': ('Pommes Frites', 'Frittierte Kartoffeln.'),
    '464': ('Zwiebelringe', 'Frittierte Zwiebeln.'),
    '465': ('Brathähnchen', 'Knuspriges Hähnchen.'),
    '466': ('Hot Dog', 'Würstchen im Brötchen.'),
    '467': ('Eiscreme', 'Süßes gefrorenes Dessert.'),
    '468': ('Brownie', 'Schokoladenleckerbissen.'),
    '469': ('Schokoladenkeks', 'Gebackener Leckerbissen.'),
    '470': ('Donut', 'Frittierter Teig.'),
    '471': ('Cupcake', 'Kleiner Kuchen.'),
    '472': ('Käsekuchen', 'Reichhaltiges Dessert.'),
    '473': ('Milchshake', 'Dickes Getränk.'),
    '474': ('Nachos', 'Chips und Käse.'),
    '475': ('Kartoffelchips', 'Knuspriger Snack.'),
    '476': ('Brezel', 'Gebackenes Brot.'),
    '477': ('Popcorn', 'Gepoppter Mais.'),
    '478': ('Schokoriegel', 'Süßigkeiten.'),
    '479': ('Gummibärchen', 'Süßigkeiten.'),
    '480': ('Limonade', 'Zuckerhaltiges Getränk.'),
    '481': ('Hähnchenflügel', 'Frittierte Flügel.'),
    '482': ('Hähnchenstreifen', 'Paniertes Hähnchen.'),
    '483': ('Fish and Chips', 'Frittierter Fisch.'),
    '484': ('Pfannkuchen', 'Frühstückskuchen.'),
    '485': ('Waffeln', 'Frühstücksteig.'),
    '486': ('Arme Ritter (French Toast)', 'Eiweißbrot.'),
    '487': ('Crepes', 'Dünne Pfannkuchen.'),
    '488': ('Croissant', 'Blätterteiggebäck.'),
    '489': ('Muffin', 'Backwaren.'),
    '490': ('Bagel', 'Dichtes Brot.'),
    '491': ('Scone', 'Gebackenes Gebäck.'),
    '492': ('Keks', 'Blättriges Brot.'),
    '493': ('Zimtrolle', 'Süße Rolle.'),
    '494': ('Makkaroni mit Käse', 'Käsenudeln.'),
    '495': ('Spaghetti Bolognese', 'Nudeln mit Fleischsauce.'),
    '496': ('Fettuccine Alfredo', 'Cremige Nudeln.'),
    '497': ('Ravioli', 'Gefüllte Nudeln.'),
    '498': ('Tortellini', 'Ringnudeln.'),
    '499': ('Fleischbällchen', 'Hackfleisch.'),
    '500': ('Knoblauchbrot', 'Gebutters Brot.')
}

with open(dest_json, 'r', encoding='utf-8') as f:
    content = f.read()

# find the closing brace
content = content.rstrip()
if content.endswith('}'):
    content = content[:-1].rstrip()

# Add a comma if needed
if not content.endswith(','):
    content += ','

# Append translations
new_lines = []
for i in range(251, 501):
    id_str = str(i)
    if id_str in translations:
        name, info = translations[id_str]
        new_lines.append(f'\n  "food_{id_str}": "{name}",\n  "info_{id_str}": "{info}"')
    else:
        new_lines.append(f'\n  "food_{id_str}": "Food {id_str}",\n  "info_{id_str}": "Info {id_str}"')

content += ",".join(new_lines) + '\n}\n'

with open(dest_json, 'w', encoding='utf-8') as f:
    f.write(content)
print("Translations appended successfully.")
