import json

new_foods = {
  "food_251": "Tofu (Ferme)",
  "info_251": "Produit à base de soja riche en protéines.",
  "food_252": "Tempeh",
  "info_252": "Produit à base de soja fermenté.",
  "food_253": "Seitan",
  "info_253": "Substitut de viande au gluten de blé.",
  "food_254": "Edamame",
  "info_254": "Jeunes fèves de soja.",
  "food_255": "Lentilles",
  "info_255": "Légumineuse riche en fibres.",
  "food_256": "Pois Chiches",
  "info_256": "Légumineuse ronde et dorée.",
  "food_257": "Haricots Noirs",
  "info_257": "Légumineuse populaire.",
  "food_258": "Quinoa",
  "info_258": "Protéine végétale complète.",
  "food_259": "Graines de Chia",
  "info_259": "Graines riches en fibres.",
  "food_260": "Cœurs de Chanvre",
  "info_260": "Riche en oméga-3.",
  "food_261": "Levure Nutritionnelle",
  "info_261": "Arôme végétalien au goût de fromage.",
  "food_262": "Lait de Soja",
  "info_262": "Lait sans produits laitiers.",
  "food_263": "Lait d'Avoine",
  "info_263": "Lait végétalien crémeux.",
  "food_264": "Isolat de Protéine de Pois",
  "info_264": "Poudre de protéine végétale.",
  "food_265": "Falafel",
  "info_265": "Boulettes de pois chiches frites.",
  "food_266": "Houmous",
  "info_266": "Trempette aux pois chiches.",
  "food_267": "Galette de Burger Végétalien",
  "info_267": "Viande végétale.",
  "food_268": "Fruit du Jacquier",
  "info_268": "Substitut de viande texturé.",
  "food_269": "Beurre d'Amande",
  "info_269": "Pâte à tartiner aux noix.",
  "food_270": "Fromage de Noix de Cajou",
  "info_270": "Alternative au fromage végétalien.",
  "food_271": "Galette Beyond Burger",
  "info_271": "Burger végétalien populaire.",
  "food_272": "Galette Impossible Burger",
  "info_272": "Alternative à la viande végétale.",
  "food_273": "Saucisse Végétalienne",
  "info_273": "Saucisse végétale.",
  "food_274": "Bacon Végétalien",
  "info_274": "Lanières végétaliennes fumées.",
  "food_275": "Mayonnaise Végétalienne",
  "info_275": "Mayonnaise sans œufs.",
  "food_276": "Nectar d'Agave",
  "info_276": "Édulcorant végétalien.",
  "food_277": "Sirop d'Érable",
  "info_277": "Sirop naturel.",
  "food_278": "Yaourt de Soja",
  "info_278": "Yaourt sans produits laitiers.",
  "food_279": "Yaourt de Coco",
  "info_279": "Yaourt végétalien crémeux.",
  "food_280": "Lait de Macadamia",
  "info_280": "Lait de noix.",
  "food_281": "Lait de Noix de Cajou",
  "info_281": "Lait de noix peu calorique.",
  "food_282": "Lait de Coco (En conserve)",
  "info_282": "Lait culinaire riche.",
  "food_283": "Lait d'Amande (Non sucré)",
  "info_283": "Alternative laitière peu calorique.",
  "food_284": "Haricots Rouges",
  "info_284": "Gros haricots rouges.",
  "food_285": "Haricots Blancs (Navy)",
  "info_285": "Petits haricots blancs.",
  "food_286": "Haricots Pinto",
  "info_286": "Haricot commun.",
  "food_287": "Haricots Cannellini",
  "info_287": "Gros haricots blancs.",
  "food_288": "Grands Haricots Blancs",
  "info_288": "Haricots blancs moyens.",
  "food_289": "Haricots de Lima",
  "info_289": "Haricots beurre.",
  "food_290": "Fèves",
  "info_290": "Gros haricots.",
  "food_291": "Avocat",
  "info_291": "Riche en bonnes graisses.",
  "food_292": "Noix de Macadamia",
  "info_292": "Noix céto riche en graisses.",
  "food_293": "Noix de Pécan",
  "info_293": "Noix compatible avec le régime céto.",
  "food_294": "Noix du Brésil",
  "info_294": "Riche en sélénium.",
  "food_295": "Olives",
  "info_295": "Source de graisses saines.",
  "food_296": "Huile de Coco",
  "info_296": "Source de graisse pure.",
  "food_297": "Huile TCM",
  "info_297": "Triglycérides à chaîne moyenne.",
  "food_298": "Ghee",
  "info_298": "Beurre clarifié.",
  "food_299": "Bacon",
  "info_299": "Graisse de porc croustillante.",
  "food_300": "Couennes de Porc",
  "info_300": "Peau de porc frite.",
  "food_301": "Saumon",
  "info_301": "Poisson gras.",
  "food_302": "Sardines",
  "info_302": "Petits poissons gras.",
  "food_303": "Maquereau",
  "info_303": "Riche en oméga-3.",
  "food_304": "Crème Épaisse",
  "info_304": "Produit laitier riche en graisses.",
  "food_305": "Fromage à la Crème",
  "info_305": "Fromage doux et riche.",
  "food_306": "Brie",
  "info_306": "Fromage à pâte molle.",
  "food_307": "Camembert",
  "info_307": "Fromage français à pâte molle.",
  "food_308": "Courgette",
  "info_308": "Légume pauvre en glucides.",
  "food_309": "Chou-fleur",
  "info_309": "Incontournable du régime céto.",
  "food_310": "Asperge",
  "info_310": "Tiges pauvres en glucides.",
  "food_311": "Œufs (Entiers)",
  "info_311": "Source de protéines nutritive.",
  "food_312": "Faux-filet",
  "info_312": "Coupe de bœuf grasse.",
  "food_313": "Huile d'Avocat",
  "info_313": "Huile de cuisson à haute température.",
  "food_314": "Huile d'Olive",
  "info_314": "Huile saine pour le cœur.",
  "food_315": "Huile de Noix",
  "info_315": "Huile au goût de noix.",
  "food_316": "Huile de Sésame",
  "info_316": "Huile de cuisson aromatique.",
  "food_317": "Huile de Graines de Lin",
  "info_317": "Riche en oméga-3 ALA.",
  "food_318": "Graines de Citrouille",
  "info_318": "Pépites.",
  "food_319": "Graines de Tournesol",
  "info_319": "Graines nutritives.",
  "food_320": "Pignons de Pin",
  "info_320": "Pignons.",
  "food_321": "Pistaches",
  "info_321": "Noix vertes.",
  "food_322": "Noisettes",
  "info_322": "Fruits secs à coque.",
  "food_323": "Cheddar",
  "info_323": "Fromage au goût prononcé.",
  "food_324": "Fromage Suisse",
  "info_324": "Fromage à trous.",
  "food_325": "Provolone",
  "info_325": "Fromage italien.",
  "food_326": "Gouda",
  "info_326": "Fromage néerlandais.",
  "food_327": "Havarti",
  "info_327": "Fromage danois.",
  "food_328": "Pepper Jack",
  "info_328": "Fromage épicé.",
  "food_329": "Fromage Feta",
  "info_329": "Fromage friable.",
  "food_330": "Fromage de Chèvre",
  "info_330": "Chèvre.",
  "food_331": "Maki Sushi",
  "info_331": "Mélange de sushis.",
  "food_332": "Pad Thaï",
  "info_332": "Plat de nouilles thaïlandais.",
  "food_333": "Poulet Tikka Masala",
  "info_333": "Curry indien.",
  "food_334": "Taco au Bœuf",
  "info_334": "Taco mexicain.",
  "food_335": "Burrito",
  "info_335": "Grand wrap.",
  "food_336": "Phô",
  "info_336": "Soupe vietnamienne.",
  "food_337": "Ramen",
  "info_337": "Soupe de nouilles japonaise.",
  "food_338": "Dim Sum",
  "info_338": "Boulettes chinoises.",
  "food_339": "Samoussa",
  "info_339": "Pâtisserie frite.",
  "food_340": "Gyros",
  "info_340": "Wrap grec à la viande.",
  "food_341": "Moussaka",
  "info_341": "Gratin grec.",
  "food_342": "Paella",
  "info_342": "Plat de riz espagnol.",
  "food_343": "Fajitas",
  "info_343": "Viande grillée et poivrons.",
  "food_344": "Enchiladas",
  "info_344": "Tortillas roulées.",
  "food_345": "Churros",
  "info_345": "Pâte frite.",
  "food_346": "Pain Naan",
  "info_346": "Pain plat indien.",
  "food_347": "Bibimbap",
  "info_347": "Bol de riz coréen.",
  "food_348": "Kimchi",
  "info_348": "Chou fermenté.",
  "food_349": "Gnocchi",
  "info_349": "Boulettes de pomme de terre.",
  "food_350": "Lasagnes",
  "info_350": "Pâtes en couches.",
  "food_351": "Tom Yum",
  "info_351": "Soupe thaï épicée.",
  "food_352": "Poulet au Beurre",
  "info_352": "Plat indien crémeux.",
  "food_353": "Shawarma au Poulet",
  "info_353": "Wrap moyen-oriental.",
  "food_354": "Kebab d'Agneau",
  "info_354": "Agneau grillé.",
  "food_355": "Kofta de Bœuf",
  "info_355": "Boulettes de viande épicées.",
  "food_356": "Pain Pita",
  "info_356": "Pain plat.",
  "food_357": "Tzatzíki",
  "info_357": "Trempette au yaourt.",
  "food_358": "Baba Ganousch",
  "info_358": "Trempette d'aubergine.",
  "food_359": "Dolma",
  "info_359": "Feuilles de vigne farcies.",
  "food_360": "Spanakópita",
  "info_360": "Tourte aux épinards.",
  "food_361": "Baklava",
  "info_361": "Pâtisserie sucrée.",
  "food_362": "Tiramisu",
  "info_362": "Dessert italien.",
  "food_363": "Gelato",
  "info_363": "Crème glacée italienne.",
  "food_364": "Soupe Miso",
  "info_364": "Soupe japonaise.",
  "food_365": "Wakame",
  "info_365": "Salade d'algues.",
  "food_366": "Nouilles Soba",
  "info_366": "Nouilles de sarrasin.",
  "food_367": "Nouilles Udon",
  "info_367": "Nouilles de blé épaisses.",
  "food_368": "Matcha",
  "info_368": "Poudre de thé vert.",
  "food_369": "Taro",
  "info_369": "Légume racine.",
  "food_370": "Bubble Tea",
  "info_370": "Thé aux perles.",
  "food_371": "Rouleau de Printemps",
  "info_371": "Rouleau frit.",
  "food_372": "Pâté Impérial (Egg Roll)",
  "info_372": "Apéritif chinois.",
  "food_373": "Soupe Wonton",
  "info_373": "Soupe aux raviolis.",
  "food_374": "Calamars Frits",
  "info_374": "Calmars frits.",
  "food_375": "Bâtonnets de Mozzarella",
  "info_375": "Fromage frit.",
  "food_376": "Jalapeño Poppers",
  "info_376": "Piments farcis.",
  "food_377": "Tater Tots",
  "info_377": "Pommes de terre frites.",
  "food_378": "Rösti (Hash Browns)",
  "info_378": "Pommes de terre pour le petit-déjeuner.",
  "food_379": "Beignet de Saucisse (Corn Dog)",
  "info_379": "Saucisse panée.",
  "food_380": "Pâtes au Pesto",
  "info_380": "Pâtes à la sauce au basilic.",
  "food_381": "Protéine de Lactosérum (Whey)",
  "info_381": "Protéine laitière.",
  "food_382": "Protéine de Caséine",
  "info_382": "Protéine à digestion lente.",
  "food_383": "BCAA",
  "info_383": "Acides aminés à chaîne ramifiée.",
  "food_384": "Créatine",
  "info_384": "Complément de performance.",
  "food_385": "Pré-entraînement (Pre-workout)",
  "info_385": "Booster d'énergie.",
  "food_386": "Barre Protéinée",
  "info_386": "Collation pratique.",
  "food_387": "Mass Gainer",
  "info_387": "Poudre hypercalorique.",
  "food_388": "Peptides de Collagène",
  "info_388": "Soutien articulaire.",
  "food_389": "Boisson Électrolytique",
  "info_389": "Hydratation.",
  "food_390": "Boisson Énergisante",
  "info_390": "Boisson caféinée.",
  "food_391": "Biscuit Protéiné",
  "info_391": "Douceur protéinée.",
  "food_392": "Substitut de Repas",
  "info_392": "Nutrition équilibrée.",
  "food_393": "Glutamine",
  "info_393": "Acide aminé pour la récupération.",
  "food_394": "Huile de Poisson",
  "info_394": "Pilules d'oméga-3.",
  "food_395": "Gommes Multivitaminées",
  "info_395": "Vitamines.",
  "food_396": "Barre Quest",
  "info_396": "Barre protéinée populaire.",
  "food_397": "Barre RxBar",
  "info_397": "Barre d'aliments complets.",
  "food_398": "Barre Clif",
  "info_398": "Barre énergétique.",
  "food_399": "Barre Larabar",
  "info_399": "Barre aux fruits et noix.",
  "food_400": "Barre Keto",
  "info_400": "Barre pauvre en glucides.",
  "food_401": "Eau Protéinée",
  "info_401": "Eau infusée.",
  "food_402": "Kombucha",
  "info_402": "Thé fermenté.",
  "food_403": "Café Infusé à Froid",
  "info_403": "Café fort.",
  "food_404": "Thé Vert",
  "info_404": "Boisson antioxydante.",
  "food_405": "Thé Noir",
  "info_405": "Thé caféiné.",
  "food_406": "Farine d'Amande",
  "info_406": "Cuisson céto.",
  "food_407": "Farine de Coco",
  "info_407": "Farine riche en fibres.",
  "food_408": "Farine de Tapioca",
  "info_408": "Amidon sans gluten.",
  "food_409": "Farine de Manioc",
  "info_409": "Farine de racine.",
  "food_410": "Poudre d'Arrow-root",
  "info_410": "Agent épaississant.",
  "food_411": "Myrtilles",
  "info_411": "Riche en antioxydants.",
  "food_412": "Fraises",
  "info_412": "Baies sucrées.",
  "food_413": "Framboises",
  "info_413": "Baies riches en fibres.",
  "food_414": "Mûres",
  "info_414": "Baies foncées.",
  "food_415": "Mangue",
  "info_415": "Fruit tropical.",
  "food_416": "Ananas",
  "info_416": "Fruit tropical sucré.",
  "food_417": "Kiwi",
  "info_417": "Riche en vitamine C.",
  "food_418": "Papaye",
  "info_418": "Enzymes digestives.",
  "food_419": "Pastèque",
  "info_419": "Melon hydratant.",
  "food_420": "Cantaloup",
  "info_420": "Melon orange.",
  "food_421": "Melon Miel (Honeydew)",
  "info_421": "Melon vert.",
  "food_422": "Pêche",
  "info_422": "Fruit à noyau.",
  "food_423": "Prune",
  "info_423": "Fruit sucré.",
  "food_424": "Cerise",
  "info_424": "Petit fruit.",
  "food_425": "Pamplemousse",
  "info_425": "Agrume.",
  "food_426": "Grenade",
  "info_426": "Fruit à pépins.",
  "food_427": "Figue",
  "info_427": "Douce et moelleuse.",
  "food_428": "Dattes",
  "info_428": "Fruit hautement énergétique.",
  "food_429": "Épinards",
  "info_429": "Légume vert à feuilles.",
  "food_430": "Chou Frisé (Kale)",
  "info_430": "Superaliment vert.",
  "food_431": "Roquette",
  "info_431": "Légume vert poivré.",
  "food_432": "Bok Choy",
  "info_432": "Chou asiatique.",
  "food_433": "Bettes",
  "info_433": "Légume riche en nutriments.",
  "food_434": "Chou Cavalier",
  "info_434": "Légumes verts consistants.",
  "food_435": "Choux de Bruxelles",
  "info_435": "Mini choux.",
  "food_436": "Brocoli",
  "info_436": "Légume crucifère.",
  "food_437": "Chou",
  "info_437": "Légume croquant.",
  "food_438": "Carottes",
  "info_438": "Légume racine.",
  "food_439": "Betteraves",
  "info_439": "Légume racine rouge.",
  "food_440": "Radis",
  "info_440": "Racine épicée.",
  "food_441": "Navet",
  "info_441": "Légume racine.",
  "food_442": "Panais",
  "info_442": "Racine sucrée.",
  "food_443": "Patate Douce",
  "info_443": "Tubercule orange.",
  "food_444": "Igname",
  "info_444": "Racine féculente.",
  "food_445": "Courge",
  "info_445": "Courge d'été.",
  "food_446": "Citrouille",
  "info_446": "Courge d'hiver.",
  "food_447": "Artichaut",
  "info_447": "Bourgeon de chardon.",
  "food_448": "Aubergine",
  "info_448": "Légume violet.",
  "food_449": "Courge Jaune",
  "info_449": "Légume d'été.",
  "food_450": "Courge Butternut",
  "info_450": "Courge d'hiver douce.",
  "food_451": "Courge Poivrée",
  "info_451": "Courge d'hiver.",
  "food_452": "Courge Spaghetti",
  "info_452": "Alternative aux pâtes.",
  "food_453": "Poireaux",
  "info_453": "Oignon doux.",
  "food_454": "Oignons Verts",
  "info_454": "Cébettes.",
  "food_455": "Canneberges",
  "info_455": "Baies acidulées.",
  "food_456": "Groseilles à Maquereau",
  "info_456": "Baies acides.",
  "food_457": "Fruit de la Passion",
  "info_457": "Fruit tropical.",
  "food_458": "Fruit du Dragon",
  "info_458": "Pitaya.",
  "food_459": "Litchi",
  "info_459": "Fruit sucré.",
  "food_460": "Mangoustan",
  "info_460": "Délice tropical.",
  "food_461": "Part de Pizza",
  "info_461": "Fromage et tomate.",
  "food_462": "Cheeseburger",
  "info_462": "Bœuf et fromage.",
  "food_463": "Frites",
  "info_463": "Pommes de terre frites.",
  "food_464": "Rondelles d'Oignon",
  "info_464": "Oignons frits.",
  "food_465": "Poulet Frit",
  "info_465": "Poulet croustillant.",
  "food_466": "Hot-dog",
  "info_466": "Saucisse dans un pain.",
  "food_467": "Crème Glacée",
  "info_467": "Dessert glacé sucré.",
  "food_468": "Brownie",
  "info_468": "Gourmandise au chocolat.",
  "food_469": "Cookie aux Pépites de Chocolat",
  "info_469": "Gourmandise cuite au four.",
  "food_470": "Beignet (Donut)",
  "info_470": "Pâte frite.",
  "food_471": "Cupcake",
  "info_471": "Petit gâteau.",
  "food_472": "Cheesecake",
  "info_472": "Dessert riche.",
  "food_473": "Milkshake",
  "info_473": "Boisson épaisse.",
  "food_474": "Nachos",
  "info_474": "Chips et fromage.",
  "food_475": "Chips de Pomme de Terre",
  "info_475": "Snack croustillant.",
  "food_476": "Bretzel",
  "info_476": "Produit de boulangerie.",
  "food_477": "Pop-corn",
  "info_477": "Maïs soufflé.",
  "food_478": "Barre Chocolatée",
  "info_478": "Barre au chocolat.",
  "food_479": "Oursons en Gélatine",
  "info_479": "Bonbon sucré.",
  "food_480": "Soda",
  "info_480": "Boisson sucrée.",
  "food_481": "Ailes de Poulet",
  "info_481": "Ailes frites.",
  "food_482": "Aiguillettes de Poulet",
  "info_482": "Poulet pané.",
  "food_483": "Fish and Chips",
  "info_483": "Poisson frit.",
  "food_484": "Pancakes",
  "info_484": "Gâteaux du petit-déjeuner.",
  "food_485": "Gaufres",
  "info_485": "Pâte du petit-déjeuner.",
  "food_486": "Pain Perdu",
  "info_486": "Pain aux œufs.",
  "food_487": "Crêpes",
  "info_487": "Pancakes fins.",
  "food_488": "Croissant",
  "info_488": "Pâtisserie feuilletée.",
  "food_489": "Muffin",
  "info_489": "Produit de boulangerie.",
  "food_490": "Bagel",
  "info_490": "Pain dense.",
  "food_491": "Scone",
  "info_491": "Pâtisserie cuite.",
  "food_492": "Biscuit (Américain)",
  "info_492": "Pain feuilleté.",
  "food_493": "Roulé à la Cannelle",
  "info_493": "Roulé sucré.",
  "food_494": "Macaroni au Fromage",
  "info_494": "Pâtes au fromage.",
  "food_495": "Spaghettis Bolognaise",
  "info_495": "Pâtes à la sauce à la viande.",
  "food_496": "Fettuccine Alfredo",
  "info_496": "Pâtes crémeuses.",
  "food_497": "Raviolis",
  "info_497": "Pâtes farcies.",
  "food_498": "Tortellinis",
  "info_498": "Pâtes en anneau.",
  "food_499": "Boulettes de Viande",
  "info_499": "Viande hachée.",
  "food_500": "Pain à l'Ail",
  "info_500": "Pain beurré à l'ail."
}

def update_json_file(file_path, new_data):
    with open(file_path, 'r', encoding='utf-8') as file:
        data = json.load(file)
    
    data.update(new_data)
    
    with open(file_path, 'w', encoding='utf-8') as file:
        json.dump(data, file, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    file_path = r"c:\Users\bayta\OneDrive\Masaüstü\fitness\src\locales\fr.json"
    update_json_file(file_path, new_foods)
    print("Updated JSON file successfully.")
