import json

translations = {
  "food_251": "Tofu (Fermo)", "info_251": "Prodotto a base di soia ad alto contenuto proteico.",
  "food_252": "Tempeh", "info_252": "Prodotto di soia fermentato.",
  "food_253": "Seitan", "info_253": "Sostituto della carne a base di glutine di grano.",
  "food_254": "Edamame", "info_254": "Semi di soia giovani.",
  "food_255": "Lenticchie", "info_255": "Legume ricco di fibre.",
  "food_256": "Ceci", "info_256": "Fagioli garbanzo.",
  "food_257": "Fagioli Neri", "info_257": "Legume popolare.",
  "food_258": "Quinoa", "info_258": "Proteina vegetale completa.",
  "food_259": "Semi di Chia", "info_259": "Semi ad alto contenuto di fibre.",
  "food_260": "Cuori di Canapa", "info_260": "Ricchi di omega-3.",
  "food_261": "Lievito Alimentare", "info_261": "Aroma vegano al sapore di formaggio.",
  "food_262": "Latte di Soia", "info_262": "Latte senza lattosio.",
  "food_263": "Latte d'Avena", "info_263": "Latte vegano cremoso.",
  "food_264": "Isolato di Proteine di Pisello", "info_264": "Proteine in polvere a base vegetale.",
  "food_265": "Falafel", "info_265": "Polpette di ceci fritte.",
  "food_266": "Hummus", "info_266": "Salsa di ceci.",
  "food_267": "Burger Vegano", "info_267": "Carne a base vegetale.",
  "food_268": "Jackfruit", "info_268": "Sostituto per consistenza della carne.",
  "food_269": "Burro di Mandorle", "info_269": "Crema di noci.",
  "food_270": "Formaggio di Anacardi", "info_270": "Alternativa vegana al formaggio.",
  "food_271": "Burger Beyond", "info_271": "Burger vegano popolare.",
  "food_272": "Burger Impossible", "info_272": "Alternativa alla carne a base vegetale.",
  "food_273": "Salsiccia Vegana", "info_273": "Salsiccia a base vegetale.",
  "food_274": "Bacon Vegano", "info_274": "Strisce vegane affumicate.",
  "food_275": "Maionese Vegana", "info_275": "Maionese senza uova.",
  "food_276": "Nettare di Agave", "info_276": "Dolcificante vegano.",
  "food_277": "Sciroppo d'Acero", "info_277": "Sciroppo naturale.",
  "food_278": "Yogurt di Soia", "info_278": "Yogurt senza lattosio.",
  "food_279": "Yogurt al Cocco", "info_279": "Yogurt vegano cremoso.",
  "food_280": "Latte di Macadamia", "info_280": "Latte di noci.",
  "food_281": "Latte di Anacardi", "info_281": "Latte di noci a basso contenuto calorico.",
  "food_282": "Latte di Cocco (In Lattina)", "info_282": "Latte culinario ricco.",
  "food_283": "Latte di Mandorle (Non Zuccherato)", "info_283": "Alternativa ai latticini a basso contenuto calorico.",
  "food_284": "Fagioli Rossi", "info_284": "Fagioli rossi.",
  "food_285": "Fagioli Navy", "info_285": "Fagioli bianchi.",
  "food_286": "Fagioli Pinto", "info_286": "Fagiolo comune.",
  "food_287": "Fagioli Cannellini", "info_287": "Fagioli bianchi grandi.",
  "food_288": "Fagioli Bianchi Medi", "info_288": "Fagioli bianchi medi.",
  "food_289": "Fagioli di Lima", "info_289": "Fagioli burro.",
  "food_290": "Fave", "info_290": "Fave larghe.",
  "food_291": "Avocado", "info_291": "Alto contenuto di grassi sani.",
  "food_292": "Noci di Macadamia", "info_292": "Noci chetogeniche ad alto contenuto di grassi.",
  "food_293": "Noci Pecan", "info_293": "Noci amiche del keto.",
  "food_294": "Noci del Brasile", "info_294": "Ricche di selenio.",
  "food_295": "Olive", "info_295": "Fonte di grassi sani.",
  "food_296": "Olio di Cocco", "info_296": "Fonte di grassi puri.",
  "food_297": "Olio MCT", "info_297": "Trigliceridi a catena media.",
  "food_298": "Ghee", "info_298": "Burro chiarificato.",
  "food_299": "Pancetta", "info_299": "Grasso di maiale croccante.",
  "food_300": "Cotiche di Maiale", "info_300": "Pelle di maiale fritta.",
  "food_301": "Salmone", "info_301": "Pesce grasso.",
  "food_302": "Sardine", "info_302": "Piccolo pesce azzurro.",
  "food_303": "Sgombro", "info_303": "Ricco di omega-3.",
  "food_304": "Panna Montata", "info_304": "Latticino ad alto contenuto di grassi.",
  "food_305": "Formaggio Spalmabile", "info_305": "Formaggio morbido e ricco.",
  "food_306": "Brie", "info_306": "Formaggio cremoso morbido.",
  "food_307": "Camembert", "info_307": "Formaggio francese morbido.",
  "food_308": "Zucchine", "info_308": "Verdura a basso contenuto di carboidrati.",
  "food_309": "Cavolfiore", "info_309": "Base chetogenica.",
  "food_310": "Asparagi", "info_310": "Punte a basso contenuto di carboidrati.",
  "food_311": "Uova (Intere)", "info_311": "Fonte di proteine nutrienti.",
  "food_312": "Bistecca Ribeye", "info_312": "Taglio di manzo grasso.",
  "food_313": "Olio di Avocado", "info_313": "Olio per cotture ad alta temperatura.",
  "food_314": "Olio d'Oliva", "info_314": "Olio salutare per il cuore.",
  "food_315": "Olio di Noce", "info_315": "Olio al sapore di noce.",
  "food_316": "Olio di Sesamo", "info_316": "Olio da cucina aromatico.",
  "food_317": "Olio di Semi di Lino", "info_317": "Alto contenuto di omega-3 ALA.",
  "food_318": "Semi di Zucca", "info_318": "Pepitas.",
  "food_319": "Semi di Girasole", "info_319": "Semi nutrienti.",
  "food_320": "Pinoli", "info_320": "Pinoli.",
  "food_321": "Pistacchi", "info_321": "Noci verdi.",
  "food_322": "Nocciole", "info_322": "Nocciole.",
  "food_323": "Formaggio Cheddar", "info_323": "Formaggio saporito.",
  "food_324": "Formaggio Svizzero", "info_324": "Formaggio coi buchi.",
  "food_325": "Provolone", "info_325": "Formaggio italiano.",
  "food_326": "Gouda", "info_326": "Formaggio olandese.",
  "food_327": "Havarti", "info_327": "Formaggio danese.",
  "food_328": "Pepper Jack", "info_328": "Formaggio piccante.",
  "food_329": "Formaggio Feta", "info_329": "Formaggio friabile.",
  "food_330": "Formaggio di Capra", "info_330": "Chèvre.",
  "food_331": "Rotolo di Sushi", "info_331": "Sushi misto.",
  "food_332": "Pad Thai", "info_332": "Piatto di noodles thailandese.",
  "food_333": "Pollo Tikka Masala", "info_333": "Curry indiano.",
  "food_334": "Taco di Manzo", "info_334": "Taco messicano.",
  "food_335": "Burrito", "info_335": "Involtino grande.",
  "food_336": "Pho", "info_336": "Zuppa vietnamita.",
  "food_337": "Ramen", "info_337": "Zuppa di noodles giapponese.",
  "food_338": "Dim Sum", "info_338": "Ravioli cinesi.",
  "food_339": "Samosa", "info_339": "Pasta fritta.",
  "food_340": "Gyros", "info_340": "Involtino di carne greca.",
  "food_341": "Moussaka", "info_341": "Sformato greco.",
  "food_342": "Paella", "info_342": "Piatto di riso spagnolo.",
  "food_343": "Fajitas", "info_343": "Carne e peperoni grigliati.",
  "food_344": "Enchiladas", "info_344": "Tortillas arrotolate.",
  "food_345": "Churros", "info_345": "Impasto fritto.",
  "food_346": "Pane Naan", "info_346": "Focaccia indiana.",
  "food_347": "Bibimbap", "info_347": "Ciotola di riso coreana.",
  "food_348": "Kimchi", "info_348": "Cavolo fermentato.",
  "food_349": "Gnocchi", "info_349": "Gnocchi di patate.",
  "food_350": "Lasagne", "info_350": "Pasta a strati.",
  "food_351": "Tom Yum", "info_351": "Zuppa piccante thailandese.",
  "food_352": "Butter Chicken", "info_352": "Piatto indiano cremoso.",
  "food_353": "Shawarma di Pollo", "info_353": "Involtino mediorientale.",
  "food_354": "Kebab di Agnello", "info_354": "Agnello alla griglia.",
  "food_355": "Kofta di Manzo", "info_355": "Polpette speziate.",
  "food_356": "Pane Pita", "info_356": "Focaccia.",
  "food_357": "Tzatziki", "info_357": "Salsa allo yogurt.",
  "food_358": "Baba Ganoush", "info_358": "Salsa di melanzane.",
  "food_359": "Dolma", "info_359": "Foglie di vite ripiene.",
  "food_360": "Spanakopita", "info_360": "Torta di spinaci.",
  "food_361": "Baklava", "info_361": "Dolce di pasta sfoglia.",
  "food_362": "Tiramisù", "info_362": "Dolce italiano.",
  "food_363": "Gelato", "info_363": "Gelato italiano.",
  "food_364": "Zuppa di Miso", "info_364": "Zuppa giapponese.",
  "food_365": "Wakame", "info_365": "Insalata di alghe.",
  "food_366": "Noodles Soba", "info_366": "Noodles di grano saraceno.",
  "food_367": "Noodles Udon", "info_367": "Noodles spessi di grano.",
  "food_368": "Matcha", "info_368": "Polvere di tè verde.",
  "food_369": "Taro", "info_369": "Radice vegetale.",
  "food_370": "Boba Tea", "info_370": "Bubble tea.",
  "food_371": "Involtino Primavera", "info_371": "Involtino fritto.",
  "food_372": "Involtino all'Uovo", "info_372": "Antipasto cinese.",
  "food_373": "Zuppa Wonton", "info_373": "Zuppa con ravioli.",
  "food_374": "Calamari Fritti", "info_374": "Calamari fritti.",
  "food_375": "Bastoncini di Mozzarella", "info_375": "Formaggio fritto.",
  "food_376": "Jalapeno Poppers", "info_376": "Peperoni ripieni.",
  "food_377": "Tater Tots", "info_377": "Patate fritte.",
  "food_378": "Frittelle di Patate", "info_378": "Patate per colazione.",
  "food_379": "Corn Dog", "info_379": "Wurstel impanato e fritto.",
  "food_380": "Pasta al Pesto", "info_380": "Pasta con salsa al basilico.",
  "food_381": "Proteine del Siero del Latte", "info_381": "Proteine del latte.",
  "food_382": "Proteine della Caseina", "info_382": "Proteine a digestione lenta.",
  "food_383": "BCAA", "info_383": "Aminoacidi a catena ramificata.",
  "food_384": "Creatina", "info_384": "Integratore per prestazioni.",
  "food_385": "Pre-allenamento", "info_385": "Spinta di energia.",
  "food_386": "Barretta Proteica", "info_386": "Spuntino pratico.",
  "food_387": "Mass Gainer", "info_387": "Polvere ipercalorica.",
  "food_388": "Peptidi di Collagene", "info_388": "Supporto per le articolazioni.",
  "food_389": "Bevanda Elettrolitica", "info_389": "Idratazione.",
  "food_390": "Bevanda Energetica", "info_390": "Bevanda con caffeina.",
  "food_391": "Biscotto Proteico", "info_391": "Dolce proteico.",
  "food_392": "Frullato Sostitutivo del Pasto", "info_392": "Nutrizione bilanciata.",
  "food_393": "Glutammina", "info_393": "Aminoacido per recupero.",
  "food_394": "Olio di Pesce", "info_394": "Pillole di omega-3.",
  "food_395": "Gommose Multivitaminiche", "info_395": "Vitamine.",
  "food_396": "Barretta Quest", "info_396": "Barretta proteica popolare.",
  "food_397": "RxBar", "info_397": "Barretta a base di cibi integrali.",
  "food_398": "Barretta Clif", "info_398": "Barretta energetica.",
  "food_399": "Larabars", "info_399": "Barretta di frutta e noci.",
  "food_400": "Barretta Keto", "info_400": "Barretta a basso contenuto di carboidrati.",
  "food_401": "Acqua Proteica", "info_401": "Acqua infusa.",
  "food_402": "Kombucha", "info_402": "Tè fermentato.",
  "food_403": "Caffè Cold Brew", "info_403": "Caffè forte.",
  "food_404": "Tè Verde", "info_404": "Bevanda antiossidante.",
  "food_405": "Tè Nero", "info_405": "Tè con caffeina.",
  "food_406": "Farina di Mandorle", "info_406": "Base chetogenica per dolci.",
  "food_407": "Farina di Cocco", "info_407": "Farina ad alto contenuto di fibre.",
  "food_408": "Farina di Tapioca", "info_408": "Amido senza glutine.",
  "food_409": "Farina di Manioca", "info_409": "Farina di radice.",
  "food_410": "Polvere di Maranta", "info_410": "Agente addensante.",
  "food_411": "Mirtilli", "info_411": "Ricchi di antiossidanti.",
  "food_412": "Fragole", "info_412": "Bache dolci.",
  "food_413": "Lamponi", "info_413": "Bacche ricche di fibre.",
  "food_414": "More", "info_414": "Bacche scure.",
  "food_415": "Mango", "info_415": "Frutto tropicale.",
  "food_416": "Ananas", "info_416": "Dolce tropicale.",
  "food_417": "Kiwi", "info_417": "Alto contenuto di vitamina C.",
  "food_418": "Papaya", "info_418": "Enzimi digestivi.",
  "food_419": "Anguria", "info_419": "Melone idratante.",
  "food_420": "Melone", "info_420": "Melone arancione.",
  "food_421": "Melata", "info_421": "Melone verde.",
  "food_422": "Pesca", "info_422": "Frutto a nocciolo.",
  "food_423": "Prugna", "info_423": "Frutto dolce.",
  "food_424": "Ciliegia", "info_424": "Piccolo frutto.",
  "food_425": "Pompelmo", "info_425": "Agrume.",
  "food_426": "Melograno", "info_426": "Frutto a semi.",
  "food_427": "Fico", "info_427": "Dolce e morbido.",
  "food_428": "Datteri", "info_428": "Frutto ad alta energia.",
  "food_429": "Spinaci", "info_429": "Verdura a foglia.",
  "food_430": "Cavolo Nero", "info_430": "Verdura superfood.",
  "food_431": "Rucola", "info_431": "Verdura pepata.",
  "food_432": "Bok Choy", "info_432": "Cavolo asiatico.",
  "food_433": "Bietola", "info_433": "Densa di nutrienti.",
  "food_434": "Cavolo Verde", "info_434": "Verdura sostanziosa.",
  "food_435": "Cavoletti di Bruxelles", "info_435": "Mini cavoli.",
  "food_436": "Broccoli", "info_436": "Verdura crucifera.",
  "food_437": "Cavolo", "info_437": "Verdura croccante.",
  "food_438": "Carote", "info_438": "Ortaggio a radice.",
  "food_439": "Barbabietole", "info_439": "Ortaggio a radice rosso.",
  "food_440": "Ravanello", "info_440": "Radice piccante.",
  "food_441": "Rapa", "info_441": "Ortaggio a radice.",
  "food_442": "Pastinaca", "info_442": "Radice dolce.",
  "food_443": "Patata Dolce", "info_443": "Tubero arancione.",
  "food_444": "Igname", "info_444": "Radice amidacea.",
  "food_445": "Zucca Estiva", "info_445": "Zucchina.",
  "food_446": "Zucca", "info_446": "Zucca invernale.",
  "food_447": "Carciofo", "info_447": "Bocciolo di cardo.",
  "food_448": "Melanzana", "info_448": "Verdura viola.",
  "food_449": "Zucca Gialla", "info_449": "Verdura estiva.",
  "food_450": "Zucca Butternut", "info_450": "Zucca invernale dolce.",
  "food_451": "Zucca Ghianda", "info_451": "Zucca invernale.",
  "food_452": "Zucca Spaghetti", "info_452": "Alternativa alla pasta.",
  "food_453": "Porri", "info_453": "Cipolla dal sapore delicato.",
  "food_454": "Scalogno", "info_454": "Cipolle verdi.",
  "food_455": "Mirtilli Rossi", "info_455": "Bacche aspre.",
  "food_456": "Uva Spina", "info_456": "Bacche aspre.",
  "food_457": "Frutto della Passione", "info_457": "Frutto tropicale.",
  "food_458": "Frutto del Drago", "info_458": "Pitaya.",
  "food_459": "Litchi", "info_459": "Frutto dolce.",
  "food_460": "Mangostano", "info_460": "Dolcetto tropicale.",
  "food_461": "Fetta di Pizza", "info_461": "Formaggio e pomodoro.",
  "food_462": "Cheeseburger", "info_462": "Manzo e formaggio.",
  "food_463": "Patatine Fritte", "info_463": "Patate fritte.",
  "food_464": "Anelli di Cipolla", "info_464": "Cipolle fritte.",
  "food_465": "Pollo Fritto", "info_465": "Pollo croccante.",
  "food_466": "Hot Dog", "info_466": "Salsiccia nel panino.",
  "food_467": "Gelato", "info_467": "Dessert dolce freddo.",
  "food_468": "Brownie", "info_468": "Dolce al cioccolato.",
  "food_469": "Biscotto con Gocce di Cioccolato", "info_469": "Dolce da forno.",
  "food_470": "Ciambella", "info_470": "Impasto fritto.",
  "food_471": "Cupcake", "info_471": "Piccola torta.",
  "food_472": "Cheesecake", "info_472": "Dessert ricco.",
  "food_473": "Frappè", "info_473": "Bevanda densa.",
  "food_474": "Nachos", "info_474": "Patatine e formaggio.",
  "food_475": "Patatine", "info_475": "Spuntino croccante.",
  "food_476": "Pretzel", "info_476": "Prodotto da forno.",
  "food_477": "Popcorn", "info_477": "Mais scoppiato.",
  "food_478": "Barretta di Cioccolato", "info_478": "Barretta di cioccolato.",
  "food_479": "Orsetti Gommosi", "info_479": "Caramella dolce.",
  "food_480": "Bibita Gassata", "info_480": "Bevanda zuccherata.",
  "food_481": "Ali di Pollo", "info_481": "Ali fritte.",
  "food_482": "Filetti di Pollo", "info_482": "Pollo impanato.",
  "food_483": "Fish and Chips", "info_483": "Pesce fritto.",
  "food_484": "Pancake", "info_484": "Torte per colazione.",
  "food_485": "Waffle", "info_485": "Pastella per colazione.",
  "food_486": "French Toast", "info_486": "Pane all'uovo.",
  "food_487": "Crepes", "info_487": "Frittelle sottili.",
  "food_488": "Croissant", "info_488": "Pasta sfoglia.",
  "food_489": "Muffin", "info_489": "Prodotto da forno.",
  "food_490": "Bagel", "info_490": "Pane denso.",
  "food_491": "Scone", "info_491": "Dolce al forno.",
  "food_492": "Biscotto", "info_492": "Pane friabile.",
  "food_493": "Girella alla Cannella", "info_493": "Involtino dolce.",
  "food_494": "Maccheroni al Formaggio", "info_494": "Pasta al formaggio.",
  "food_495": "Spaghetti alla Bolognese", "info_495": "Pasta al ragù di carne.",
  "food_496": "Fettuccine Alfredo", "info_496": "Pasta cremosa.",
  "food_497": "Ravioli", "info_497": "Pasta ripiena.",
  "food_498": "Tortellini", "info_498": "Pasta ad anello.",
  "food_499": "Polpette", "info_499": "Carne macinata.",
  "food_500": "Pane all'Aglio", "info_500": "Pane imburrato."
}

with open(r'c:\Users\bayta\OneDrive\Masaüstü\fitness\src\locales\it.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for k, v in translations.items():
    data[k] = v

with open(r'c:\Users\bayta\OneDrive\Masaüstü\fitness\src\locales\it.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
